name: builing and pushing image to DockerHub
on:
    push:
        branches:
            - main
        paths:
            - 'ts-imageproc-app/Dockerfile'


jobs:
    publish-images:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
             #build and push to dockerhub 
            - name: build image
              run: docker build . -t abbasnur/ts-imageproc-app:v2
            - name: push image to dockerhub
              run: | # | to run multiple commands
                docker login -u abbasnur -p ${{ secrets.DOCKER_TOKEN }}
                docker push abbasnur/ts-imageproc-app:v2         